create extension if not exists pgcrypto;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'requisition_module') then
    create type public.requisition_module as enum ('M1', 'M2', 'M3', 'M4', 'M5', 'M6');
  end if;

  if not exists (select 1 from pg_type where typname = 'requisition_urgency') then
    create type public.requisition_urgency as enum ('LOW', 'MEDIUM', 'HIGH', 'URGENT');
  end if;

  if not exists (select 1 from pg_type where typname = 'requisition_status') then
    create type public.requisition_status as enum (
      'RASCUNHO',
      'ABERTO',
      'COTAÇÃO',
      'APROVAÇÃO',
      'COMPRA',
      'RECEBIMENTO',
      'CONCLUÍDO',
      'CANCELADO',
      'REJEITADO'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'quotation_status') then
    create type public.quotation_status as enum (
      'pending',
      'quoting',
      'awaiting_proposals',
      'selecting_winner',
      'completed'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'approval_decision') then
    create type public.approval_decision as enum ('pending', 'approved', 'rejected');
  end if;

  if not exists (select 1 from pg_type where typname = 'receipt_condition') then
    create type public.receipt_condition as enum ('ok', 'damaged', 'mismatch');
  end if;

  if not exists (select 1 from pg_type where typname = 'app_role') then
    create type public.app_role as enum (
      'admin',
      'solicitante',
      'comprador',
      'aprovador',
      'almoxarife'
    );
  end if;
end
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  department text,
  email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_roles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  role public.app_role not null,
  created_at timestamptz not null default now(),
  unique (user_id, role)
);

create table if not exists public.requisitions (
  id uuid primary key default gen_random_uuid(),
  ticket_sequence bigint generated by default as identity,
  ticket_number text unique,
  module public.requisition_module not null,
  title text not null,
  description text not null,
  justification text not null,
  urgency public.requisition_urgency not null default 'MEDIUM',
  status public.requisition_status not null default 'ABERTO',
  estimated_cost numeric(12, 2),
  desired_date date,
  requester_profile_id uuid references public.profiles(id) on delete set null,
  requester_name text not null,
  requester_email text,
  requester_department text,
  created_by uuid references auth.users(id) on delete set null,
  completed_at timestamptz,
  module_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.quotations (
  id uuid primary key default gen_random_uuid(),
  requisition_id uuid not null unique references public.requisitions(id) on delete cascade,
  win_criteria text,
  status public.quotation_status not null default 'pending',
  winner_supplier_id uuid,
  buyer_id uuid references auth.users(id) on delete set null,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.quotation_suppliers (
  id uuid primary key default gen_random_uuid(),
  quotation_id uuid not null references public.quotations(id) on delete cascade,
  supplier_name text not null,
  price numeric(12, 2),
  deadline date,
  notes text,
  proposal_received boolean not null default false,
  is_winner boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.approvals (
  id uuid primary key default gen_random_uuid(),
  requisition_id uuid not null unique references public.requisitions(id) on delete cascade,
  quotation_id uuid references public.quotations(id) on delete set null,
  approval_level integer not null default 1 check (approval_level between 1 and 3),
  total_value numeric(12, 2),
  decision public.approval_decision not null default 'pending',
  justification text,
  approver_id uuid references auth.users(id) on delete set null,
  decided_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.purchases (
  id uuid primary key default gen_random_uuid(),
  requisition_id uuid not null unique references public.requisitions(id) on delete cascade,
  approval_id uuid references public.approvals(id) on delete set null,
  supplier_name text,
  supplier_price numeric(12, 2),
  purchase_order_number text,
  invoice_number text,
  payment_method text,
  notes text,
  requires_receipt boolean not null default true,
  buyer_id uuid references auth.users(id) on delete set null,
  purchased_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.receipts (
  id uuid primary key default gen_random_uuid(),
  requisition_id uuid not null unique references public.requisitions(id) on delete cascade,
  purchase_id uuid references public.purchases(id) on delete set null,
  deliverer_name text,
  carrier_company text,
  condition public.receipt_condition not null,
  notes text,
  received_by uuid references auth.users(id) on delete set null,
  received_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  requisition_id uuid references public.requisitions(id) on delete cascade,
  ticket_number text,
  action text not null,
  old_status public.requisition_status,
  new_status public.requisition_status,
  actor_id uuid references auth.users(id) on delete set null,
  actor_name text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.quotations
  drop constraint if exists quotations_winner_supplier_id_fkey;

alter table public.quotations
  add constraint quotations_winner_supplier_id_fkey
  foreign key (winner_supplier_id) references public.quotation_suppliers(id) on delete set null;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.generate_ticket_number()
returns trigger
language plpgsql
as $$
declare
  sequence_number bigint;
begin
  if new.ticket_number is not null then
    return new;
  end if;

  sequence_number := coalesce(new.ticket_sequence, nextval(pg_get_serial_sequence('public.requisitions', 'ticket_sequence')));
  new.ticket_sequence := sequence_number;
  new.ticket_number := new.module::text || '-' || lpad(sequence_number::text, 6, '0');
  return new;
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, department, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.email),
    new.raw_user_meta_data ->> 'department',
    new.email
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists requisitions_generate_ticket_number on public.requisitions;
create trigger requisitions_generate_ticket_number
before insert on public.requisitions
for each row execute function public.generate_ticket_number();

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists requisitions_set_updated_at on public.requisitions;
create trigger requisitions_set_updated_at
before update on public.requisitions
for each row execute function public.set_updated_at();

drop trigger if exists quotations_set_updated_at on public.quotations;
create trigger quotations_set_updated_at
before update on public.quotations
for each row execute function public.set_updated_at();

drop trigger if exists quotation_suppliers_set_updated_at on public.quotation_suppliers;
create trigger quotation_suppliers_set_updated_at
before update on public.quotation_suppliers
for each row execute function public.set_updated_at();

drop trigger if exists approvals_set_updated_at on public.approvals;
create trigger approvals_set_updated_at
before update on public.approvals
for each row execute function public.set_updated_at();

drop trigger if exists purchases_set_updated_at on public.purchases;
create trigger purchases_set_updated_at
before update on public.purchases
for each row execute function public.set_updated_at();

drop trigger if exists receipts_set_updated_at on public.receipts;
create trigger receipts_set_updated_at
before update on public.receipts
for each row execute function public.set_updated_at();

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.user_roles enable row level security;
alter table public.requisitions enable row level security;
alter table public.quotations enable row level security;
alter table public.quotation_suppliers enable row level security;
alter table public.approvals enable row level security;
alter table public.purchases enable row level security;
alter table public.receipts enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists profiles_select_own on public.profiles;
create policy profiles_select_own
on public.profiles
for select
to authenticated
using (auth.uid() = id);

drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists user_roles_select_own on public.user_roles;
create policy user_roles_select_own
on public.user_roles
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists requisitions_authenticated_all on public.requisitions;
create policy requisitions_authenticated_all
on public.requisitions
for all
to authenticated
using (true)
with check (true);

drop policy if exists quotations_authenticated_all on public.quotations;
create policy quotations_authenticated_all
on public.quotations
for all
to authenticated
using (true)
with check (true);

drop policy if exists quotation_suppliers_authenticated_all on public.quotation_suppliers;
create policy quotation_suppliers_authenticated_all
on public.quotation_suppliers
for all
to authenticated
using (true)
with check (true);

drop policy if exists approvals_authenticated_all on public.approvals;
create policy approvals_authenticated_all
on public.approvals
for all
to authenticated
using (true)
with check (true);

drop policy if exists purchases_authenticated_all on public.purchases;
create policy purchases_authenticated_all
on public.purchases
for all
to authenticated
using (true)
with check (true);

drop policy if exists receipts_authenticated_all on public.receipts;
create policy receipts_authenticated_all
on public.receipts
for all
to authenticated
using (true)
with check (true);

drop policy if exists audit_logs_authenticated_read on public.audit_logs;
create policy audit_logs_authenticated_read
on public.audit_logs
for select
to authenticated
using (true);
